### ISSUE TITLE
Arranging the bookmarks to what i like

### ISSUE THREAD

**Issue by readmynameplease** [jesuscc1993/gbf-bookmarker#2]
hi another request is it possible to rearrange it to what I like? and is a some sort of floating widget or icon doable? on the page of GBF.

Thank you again!

**Comment by jesuscc1993** [comment]
It should be possible to rearrange the options but so far I haven't come up with any way to let the user arrange them so it's kind of on hold. Feel free to suggest anything.

Having the extension in the page is not an option, as that would inject code into it and risk detection.

**Comment by jesuscc1993** [comment]
Hi again, @readmynameplease.

I just released [version 1.0.7](https://github.com/jesuscc1993/gbf-bookmarker/releases/tag/1.0.7), which makes bookmarks sortable in the options page.
If you don't mind, please tell me if it works correctly on your end.

**Comment by readmynameplease** [comment]
thanks it's all working for me
