### ISSUE TITLE
unclear menuing

### ISSUE THREAD

**Issue by selahx** [jesuscc1993/gbf-bookmarker#6]
![image](https://github.com/jesuscc1993/gbf-bookmarker/assets/154800481/e98ec35c-6216-4263-b179-ff3e3ef1ed1c)
After instillation the extensions looked like this with seemingly no way to navigate around it.

**Comment by jesuscc1993** [comment]
Looks like Material Icons are failing to load.
Are you able to access the URL (https://fonts.googleapis.com/icon?family=Material+Icons) directly?
Does the font (https://fonts.gstatic.com/s/materialicons/v140/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) download properly to your machine?
Do you, perhaps, have some blocking (or denied permissions) in place you think may be interfering with this?
Or maybe you are overwritting the font used, somehow.

**Comment by selahx** [comment]
I do have a command-line on my browser that disabled web fonts so I could change how the font looked in game. After taking the line out the extension works as intended but now I'm interested in finding a way to have both work fine.
![image](https://github.com/jesuscc1993/gbf-bookmarker/assets/154800481/eac104b1-9109-447c-9c13-cdfcb1da2a11)

**Comment by jesuscc1993** [comment]
You can replace web fonts without needign to disable them; usually with user styles.
In fact I have one for GBF that has that as an option: [granblue-fantasy-enhancements](https://github.com/jesuscc1993/user-css/tree/develop/granblue-fantasy/granblue-fantasy-enhancements).

If you want the font alone, something like this should work:
```
/* ==UserStyle==
@name           Granblue Fantasy Font Replacer
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    Replaces the ingame font for GBF.
@author         Me
==/UserStyle== */

@-moz-document domain("game.granbluefantasy.jp") {
  body,
  .prt-user-info .prt-info-profile .btn-user-name,
  .prt-status .prt-user-name .txt-user-name {
    font-family: "YOUR_FONT_HERE", "FOT-テロップ明朝 Pro D", "Average Sans", sans-serif !important;
  }
}
```

**Comment by selahx** [comment]
Ok that's pretty nice. Thanks for the assisstance. :)
